### ISSUE TITLE
Formatting templates converted from JSON

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#10]
Feature: To re-order the keys that come out of exporting a stack and converting it to YAML.

For IAM Statements, I think the general convention is to order (in this order):
- SID
- Effect
- Action
- Resource

It'd be nice if iidy could normalize that on the output :D

**Comment by tavisrudd** [comment]
You're suggesting that regardless of the original order that `iidy` finds in the template, the output should be reordered? Should this be an optional thing? an extensible / configurable thing?

**Comment by rymndhng** [comment]
Yeah, I wonder if it'd be useful. Maps don't typically have guaranteed ordering guarantees in languages, but it'd be a nice to have feature.

**Comment by tavisrudd** [comment]
I currently respects the ordering of whatever the original template had. I'd welcome a PR.

**Comment by tavisrudd** [comment]
As I noted on Slack, I think the strange order we're seeing on conversion is coming from either Troposphere's output or the way that Cloudformation itself is storing the template associated with a stack. `iidy` just respects whatever order is in the template it gets from the Cloudformation api.

**Comment by lewisd32** [comment]
As discussed in person, here's the suggested ordering for keys in various places.
Unless otherwise specified, keys not listed here should be sorted alphabetically and put below the specified keys.
```yaml
!root
  - Description
  - Parameters
  - Outputs
  - Conditions
  - Resources
  - Mappings

Resources: !eachKey
 - Type
 - *                # Put anything else here, Properties last
 - Properties

Parameters: !eachKey
  - Description
  - Type
  - MinValue
  - MaxValue
  - MinLength
  - MaxLength

Outputs: !eachKey
  - Description
  - Value
  - Export

Policies: !each
  - PolicyName
  - PolicyDocument
PolicyDocument:
  - Version
  - Statement
AssumeRolePolicyDocument:
  - Version
  - Statement
Statement: !each
  - Sid
  - Effect
  - Action
  - Resource
  - Condition

Tags: !eachKey
  - Key
  - Value
  - PropagateAtLaunch
```
