### ISSUE TITLE
install command

### ISSUE THREAD

**Issue by pauloancheta** [unbounce/iidy#11]
It would be great to be able to run `iidy install`, it should create `stack_args.yaml` in the current directory.

- Should include everything on the example template.
- The template should be populated with `$PWD/template.yaml`.
- Tags should be populated with:
  ```yml
  Tags: # aws tags to apply to the stack
    owner: $(whomai)
    environment: $environment || development
    project: $(basename $PWD)
    lifetime: short
  ```
- Include everything else should be commented.
