### ISSUE TITLE
Stack args filter doesn't work with derived variables

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#167]
`$defs` or `$imports` that are derived from other `$defs` or `$imports` do not resolve properly for [commands that filter](https://github.com/unbounce/iidy/blob/master/src/preprocess/filter.ts) the contents of stack args.

Running `iidy template-approval request ...` with the following template:

```
$defs:
  a: 1
  b: !$ a

ApprovedTemplateLocation: !$b
...
```

will produce an error that `a` is not defined.
