### ISSUE TITLE
`!Sub` does expansion incorrectly in included files

### ISSUE THREAD

**Issue by lewisd32** [unbounce/iidy#20]
Take a template, `input-template.yaml`:
```
$imports:
  Include: include.yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  SomeBucket:
    Type: "Include"
    Properties:
      Suffix: SomeSuffix
```
With `include.yaml`:
```
$params:
  - Name: Suffix

Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub
        - "{{Prefix}}-${Foo}"
        -
          - Foo: !$ Suffix
      Property2:
        Fn::Sub:
          - "{{Prefix}}-${Foo}"
          -
            - Foo: !$ Suffix
```

When `input-template.yaml` is rendered, the output from `Fn::Sub` and `!Sub` are quite different:
```
Resources:
  SomeBucketSomething:
    Type: 'AWS:Something'
    Properties:
      Property1: !Sub 
        - '{{Prefix}}-${SomeBucketFoo}'
        - - Foo: !$include Suffix
      Property2:
        'Fn::Sub':
          - 'SomeBucket-${Foo}'
          - - Foo: SomeSuffix
```

`Fn::Sub` is correctly replacing `{{Prefix}}`, and not touching `${Foo}`.

`!Sub` should replace `{{Prefix}}` and not touch embedded `${...}` expressions unless the match the name of an in scope variable. (Like from a `$param`, `$import`, or `$defs`.)

**Comment by tavisrudd** [comment]
The prefix handling in the `!Sub` case is automatic. You don't need to manually include `{{Prefix}}`. That said, I think the real problem here is that `Foo` is a local name that is being provided to `Sub` and `iidy` isn't respecting that. The fix I propose is to detect this style of `!Sub` invocation and not autoprefix names that are provided as arguments, such as `Foo`.

**Comment by lewisd32** [comment]
I have found the need to include ``{{Prefix}}` occasionally, for example in an export name:
```
  LambdaArn:
    Value:
      !GetAtt 'Lambda.Arn'
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-{{Prefix}}-ARN"
```
For the fix, it would be nice if this:
```
$defs:
  SomeDef: defvalue
Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub "{{Prefix}}-${SomeDef}"
```
output:
```
Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: "SomeBucket-defvalue"
```

And this:
```
Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub "{{Prefix}}-${SomeDef}"
        - SomeDef: foo
```
output:
```
Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: "SomeBucket-foo"
```

So, within both `!Sub` and `Fn::Sub`:
- in the first parameter, `{{Prefix}}` is replaced with the prefix
- in the first parameter, `${var}` is
  - replaced with an iidy scope variable, if one exists.
  - left alone otherwise

**Comment by tavisrudd** [comment]
It looks like this is because you have an extra level of nesting on the second argument to `!Sub`. 
```
$params:
  - Name: Suffix

Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub
        - "{{Prefix}}-${Foo}"
        -
          - Foo: !$ Suffix
```
should be 
```
$params:
  - Name: Suffix

Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub
        - "{{Prefix}}-${Foo}"
        - Foo: !$ Suffix
```

`iidy` does the right thing when that extra nesting is removed.

**Comment by tavisrudd** [comment]
Btw, a modified form of your SomeDef example 
```
$defs:
  SomeDef: defvalue
Resources:
  Something:
    Type: "AWS:Something"
    Properties:
      Property1: !Sub
        - "{{Prefix}}-${SomeDef}"
        - SomeDef: !$ SomeDef
```
can be made to work with a one line change in `iidy`. I'll put together a PR for that.
