### ISSUE TITLE
iidy v1.10.0 $merge syntax in Resources doesn't work

### ISSUE THREAD

**Issue by dannosaur** [unbounce/iidy#223]
Given the following;

**stack.yml**

```
$imports:
  vpc: vpc.yml

Resources:
  $merge_vpc: !$ vpc.Resources
```

**vpc.yml**

```
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/8
```

The result is;

```
$ iidy render stack.yml
error Invalid resource type: undefined at Root.Resources: "V"
```
