### ISSUE TITLE
YAML pre-processor prefixing parameters when using custom resources

### ISSUE THREAD

**Issue by dannosaur** [unbounce/iidy#228]
When using custom resources that make use of parameters, when those parameters are references to CFN parameters (via `!Ref`), the values which have originated from a global section are prefixed, which then breaks the reference to the parameter.

Take this example;

**vpc.yml**
```
$params:
  - Name: ProjectName
  - Name: Environment

Resources:
  VPC:
    $global: true
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.30.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join
            - "/"
            - - !$ ProjectName
              - !$ Environment
```

**stack.yml**
```
Parameters:
  ProjectName:
    Description: The project's name
    Type: String

  Environment:
    Description: The type of environment this is provisioned for
    Type: String
    AllowedValues:
      - production
      - staging
    Default: staging

Resources:
  VPC:
    Type: VPC
    Properties:
      ProjectName: !Ref ProjectName
      Environment: !Ref Environment
```

The actual output is...

```
Parameters:
  # as the input, truncated for brevity
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.30.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join 
            - /
            - - !Ref VPCProjectName
              - !Ref VPCEnvironment
```

whereas I'd expect `!Ref ProjectName` and `!Ref Environment` to remain untouched.

Unless I'm missing something?
