### ISSUE TITLE
iidy render `!Not [!Equals ]` produces invalid YAML for CloudFormation

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#262]
### Expected
Input Template untouched

### Actual
Template pre-processed unexpectedly and CloudFormation is not happy with it.

### Input Template

```
Conditions:
  CreateAlarms: !Equals [ !Ref CreateAlarms, "yes" ]
  InitialNoop: !Equals [ !Ref CodePath, "initial-noop" ]
  CreateStreamAlarms: !Equals [ !Ref CreateAlarms, "yes" ]
  InVpc:
    !Not [!Equals [!Ref VpcStackName, "" ]]
```

### Result

```
❯ iidy render invalid_expansion.yml
Conditions:
  CreateAlarms: !Equals
    - !Ref CreateAlarms
    - 'yes'
  InitialNoop: !Equals
    - !Ref CodePath
    - initial-noop
  CreateStreamAlarms: !Equals
    - !Ref CreateAlarms
    - 'yes'
  InVpc: !Not
    _data:
      - !Ref VpcStackName
      - ''
    visited: false
    ctor: !<tag:yaml.org,2002:js/function> |-
      class AnonTag extends Tag {
              constructor() {
                  super(...arguments);
                  this.tag_name = tag_name;
              }
          }
    tag_name: Equals
```
