### ISSUE TITLE
`GetAtt` in custom resources does not prefix resource name

### ISSUE THREAD

**Issue by lewisd32** [unbounce/iidy#6]
In a custom resource (imported as `LongLivedBucket`) I have:
```yaml
Resources:
  LongLivedBucket:
    Type: "AWS::S3::Bucket"
    ...
Outputs:
  Name:
    Description: "The bucket's name"
    Value:
      !Ref LongLivedBucket
  ARN:
    Description: "The bucket's ARN"
    Value:
      !GetAtt LongLivedBucket.Arn
```

In the template I have:
```yaml
Resources:
  ConfigBucket:
    Type: LongLivedBucket
```

This renders as:
```yaml
Outputs:
  ConfigBucketName:
    Description: The bucket's name
    Value: !Ref ConfigBucketLongLivedBucket
  ConfigBucketARN:
    Description: The bucket's ARN
    Value: !GetAtt LongLivedBucket.Arn
```

The first output correctly prefixes the reference to `LongLivedBucket` with `ConfigBucket`, but the second output does not, which results in this template failing validation:
`error: Template error: instance of Fn::GetAtt references undefined resource LongLivedBucket`

Until this is fixed, a workaround is to change the `!GetAtt` to the following:
`!GetAtt '{{Prefix}}LongLivedBucket.Arn'`
