### ISSUE TITLE
!GetAtt assumes it's a string

### ISSUE THREAD

**Issue by pauloancheta** [unbounce/iidy#73]
Getting an error when `!GetAtt` is throwing an error when it is passed an array:
```yaml
# cfn-template.yaml
Resources:
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt [MyRole, Arn]
```

```sh
error: ref.trim is not a function
error:  TypeError: ref.trim is not a function
    at maybeRewriteRef (/snapshot/iidy/lib/preprocess/index.js:827:30)
    at Object.exports.visitGetAtt (/snapshot/iidy/lib/preprocess/index.js:835:60)
    at visitYamlTagNode (/snapshot/iidy/lib/preprocess/index.js:645:24)
    at result (/snapshot/iidy/lib/preprocess/index.js:882:20)
    at visitNode (/snapshot/iidy/lib/preprocess/index.js:899:7)
    at visitMapNode (/snapshot/iidy/lib/preprocess/index.js:969:46)
    at visitPlainMap (/snapshot/iidy/lib/preprocess/index.js:947:16)
    at result (/snapshot/iidy/lib/preprocess/index.js:888:20)
    at visitNode (/snapshot/iidy/lib/preprocess/index.js:899:7)
    at visitMapNode (/snapshot/iidy/lib/preprocess/index.js:969:46)
    at visitPlainMap (/snapshot/iidy/lib/preprocess/index.js:947:16)
    at result (/snapshot/iidy/lib/preprocess/index.js:888:20)
    at visitNode (/snapshot/iidy/lib/preprocess/index.js:899:7)
    at _.fromPairs._.map (/snapshot/iidy/lib/preprocess/index.js:576:24)
    at arrayMap (/snapshot/iidy/node_modules/lodash/lodash.js:660:23)
    at Function.map (/snapshot/iidy/node_modules/lodash/lodash.js:9571:14)
```

As a workaround, I'm using a string instead
```yaml
Resources:
  MyCodePipeline:
    Properties:
      RoleArn: !GetAtt MyRole.Arn
```
