### ISSUE TITLE
Make setting params easier based on stack-args

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#92]
Given a stack args like:

```
$imports:
  params: ssm-path:/path/to/params/

...
Parameters:
  ImageId: !$ params.ImageId
```

allow something like this to work:

```
iidy param set stack-args.yaml params.ImageId ami-000000
```

where `params` is the `$imports` variable name that points to a SSM parameter path. This would set `/path/to/params/ImageId` to `ami-000000`.

This should work with `iidy param --environment ...` or other imports that are used to produce the `ssm-path`.

Related, it would be nice to have `iidy param update` that fails if it isn't overwriting a parameter (the opposite of `iidy set` without `--overwrite`). This, in conjunction with the above, would prevent users from setting the wrong parameter (eg. setting the wrong path or the correct path in the wrong region).

**Comment by tavisrudd** [comment]
Any thoughts on how we'd deal with ad-hoc naming of the `$imports` or import of multiple `ssm-paths` (app-specific, shared, etc.)?

**Comment by jpb** [comment]
`params` isn't a special identifier - it could be called anything:

```
$imports:
  cats: ssm-path:/cats/
  dogs: ssm-path:/dogs/

...
Parameters:
  ImageId: !$ cats.ImageId
```

```
iidy param set stack-args.yaml cats.ImageId ami-000000
```
